command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_APP_MODE
    value: "true"
  - name: SQL_WAREHOUSE
    valueFrom: "sql-warehouse"

